name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t resource-lock-api .

    - name: Run tests inside Docker
      run: docker run --rm resource-lock-api pytest

    - name: Lint with flake8 inside Docker
      run: docker run --rm resource-lock-api flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics